# https://stackoverflow.com/questions/35868894/travis-ci-activerecordnodatabaseerror-fatal-database-jobtrak-test-does-no

language: ruby

branches:
  only:
  - master
  - staging

rvm:
 - 2.4.2

env:
  - DB=pgsql

services:
  - postgresql

script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake

# be sure to configure config/database.yml.travis too with:
# default: &default
#   adapter: postgresql
#   encoding: unicode
#   pool: 5
#
# development:
#   <<: *default
#   database: shop_development
#
# test:
#   <<: *default
#   database: shop_test
#
# production:
#   <<: *default
#   database: shop_developement

before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database shop_test;' -U postgres
