language: ruby

rvm:
 - 2.4.2

env:
  - DB=pgsql

services:
  - postgresql

script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake

# script:
#   - bin/rake db:migrate RAILS_ENV=test
#   - bin/rake

before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database shop_test;' -U postgres
